[package]
name = "gestalt_brick"
version = "0.1.1"
edition = "2018"
authors = ["https://github.com/TTTiNNNy"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
